### PR TITLE
~50x speedup vectorizing array.screenshot with numpy

### PR DESCRIPTION
**Pull request by mode80**
Not sure if you'll want this because it adds a numpy dependency, but it was necessary for my use case. (I'm using libretro.py to access arcade games for Reinforcement Learning training where speed is important.)

### CODE REVIEW

**Comment by JesseTG** [comment]
I'd rather keep dependencies for essential libretro.py functionality as slim as possible. But if you write a _new_ `NumpyVideoDriver` and make sure that...

- The new `numpy` dependency is gated behind an extra the same way [OpenGL functionality is](https://github.com/JesseTG/libretro.py/blob/main/pyproject.toml#L62-L65)
- Its feature set matches the existing `ArrayVideoDriver`
- Existing imports aren't broken if `numpy` isn't installed

...then I'd accept it.

**Comment by mode80** [comment]
That's super reasonable. In fact, the lack of complicated build steps and dependancies are what drew me to libretro.py. I hadn't thought of the NumpyVideoDriver approach but remember seeing what you did with OpenGL, so that's a good idea.

ps. Reading your code has introduced me to a lot of newer-version Python goodies I didn't know about. Thanks for your efforts on this project.

**Comment by JesseTG** [comment]
Pattern matching's a real treat, ain't it?

**Comment by JesseTG** [comment]
I'm going to close this PR to keep my backlog tidy, because this PR as it exists conflicts with the goals [I'd previously outlined](https://github.com/JesseTG/libretro.py/pull/21#issuecomment-2384702166). But if you decide to write a full-fledged `NumpyVideoDriver` and contribute it upstream, open a new PR and I'll gladly walk you through getting it integrated.

**Comment by mode80** [comment]
No worries. I found a new approach, making use of ._frame directly rather than .screenshot().  (This is faster and lets me do whatever pixel processing I need on my end without adding new dependencies to libretro.py.)

**Pull request closed without merging**
